# Path to your training, validation, and test datasets
train: D:\AI Projects\building action recognition model\AI-PackageGuard\FineTuneYOLOToDetectPeopelWithParcels\data\custom_dataset\images\train
val: D:\AI Projects\building action recognition model\AI-PackageGuard\FineTuneYOLOToDetectPeopelWithParcels\data\custom_dataset\images\val
test: D:\AI Projects\building action recognition model\AI-PackageGuard\FineTuneYOLOToDetectPeopelWithParcels\data\custom_dataset\images\test


nc: 1  # number of classes
names: ['holding parcel']
